// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTUEsK3lFeLol2hO9G_HJFEW2k3dnseU',
    appId: '1:154804557263:web:e4a975fb73291d1a29aeba',
    messagingSenderId: '154804557263',
    projectId: 'my-rate-13518',
    authDomain: 'my-rate-13518.firebaseapp.com',
    storageBucket: 'my-rate-13518.firebasestorage.app',
    measurementId: 'G-MW1DE5B2S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOnbQOwa7Kpz_OgzLkld775adl34g0zTc',
    appId: '1:154804557263:android:025717b93d7d802e29aeba',
    messagingSenderId: '154804557263',
    projectId: 'my-rate-13518',
    storageBucket: 'my-rate-13518.firebasestorage.app',
  );
}
